# Generated by Django 5.0.6 on 2024-06-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
