# Generated by Django 5.0.6 on 2024-06-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0002_league_slug_match_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
